name: Check Line Endings

on:
  # Trigger the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  crlf-check:
    name: Ensure there is no CRLF
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v2

      - name: Check CRLF line endings
        uses: gi-org-pl/check-crlf-action@v1.0.2
